apiVersion: ecns.easystack.com/v1
kind: AnsiblePlan
metadata:
  labels:
    app.kubernetes.io/name: ansibleplan
    app.kubernetes.io/instance: ansibleplan-sample
    app.kubernetes.io/part-of: easystack-eks-op
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: easystack-eks-op
  name: ansibleplan-sample
  namespace: test-capo
spec:
  foo: bar
  # TODO(user): Add fields here
