apiVersion: ecns.easystack.com/v1
kind: Plan
metadata:
  labels:
    app.kubernetes.io/name: plan
    app.kubernetes.io/instance: plan-sample
    app.kubernetes.io/part-of: easystack-eks-op
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: easystack-eks-op
  name: plan-sample
  namespace: test-capo
spec:
  mode: "new"
  k8sVersion: "1.20.14"
  cluster_name: "test1"
  ssh_key: "jian"
  use_float_ip: false
  node_cidr: "10.6.0.0/24"
  machine_sets:
    - name: "test-master"
      image: "centos-qga"
      flavor: "2C-4G"
      replica: 1
      role: "master"
      infras:
        - availability_zone: "default-az"
          volumes:
            - volume_type: "hdd"
              volume_size: 20
              index: 1
            - volume_type: "hdd"
              volume_size: 10
              index: 2
            - volume_type: "hdd"
              volume_size: 5
              index: 3

    - name: "test"
      image: "centos-qga"
      flavor: "2C-4G"
      replica: 2
      role: "node"
      infras:
        - availability_zone: "default-az"
          volumes:
            - volume_type: "hdd"
              volume_size: 20
              index: 1
            - volume_type: "hdd"
              volume_size: 10
              index: 2
            - volume_type: "hdd"
              volume_size: 5
              index: 3
        - availability_zone: "default-az"
          volumes:
            - volume_type: "hdd"
              volume_size: 20
              index: 1
            - volume_type: "hdd"
              volume_size: 10
              index: 2
            - volume_type: "hdd"
              volume_size: 5
              index: 3
  monitor:
    pvc_type: "hdd"
    pvc_cap: "10"
    auto_clear_days: "7"
  repo: "hub.easystack.io"
  cni_type: "flannel"
  pod_cidr: "10.232.0.0/14"
  svc_cidr: "10.222.0.0/16"
  ansible_plan_auto: false
  user:
    auth_url: "http://keystone.openstack.svc.cluster.local/v3"
    token: "gAAAAABkpS2RG2mUsxo7fqKYVQpH2S_MwhS63OOMefx37gtcCqw9p1TOBzmLlL5zlROHMe-O3vrDy_uS882EG1nqU0U9JsXKDtsImHR4ONr6lc3YQMvcC33BtTzJM9gFEyH3wi3HEbs3gPAdobAITOcXpZpmCCv09Ti6skantZV0tKNVrk50zD4"
    region: "RegionOne"





  # TODO(user): Add fields here
