apiVersion: ecns.easystack.com/v1
kind: Plan
metadata:
  labels:
    app.kubernetes.io/name: plan
    app.kubernetes.io/instance: plan-sample
    app.kubernetes.io/part-of: easystack-eks-op
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: easystack-eks-op
  name: plan-sample
spec:
  # TODO(user): Add fields here
